Add support for sparse metadata labelling layers
TutteInstitute/thisnotthat pull request #14
Opened 2022-12-06 16:51 UTC by lmcinnes

A simple approach to labelling when dealing with sparse metadata (e.g. bag-of-words matrices). The approach is similar to BERTopic's c-TF-IDF but uses the more advanced options available from the semi-supervised ``InformationWeightTransformer`` in ``vectorizers``, and (since we do not assume joint embeddings) doesn't look at closeness of selected keywords in the joint space.

2022-12-12 14:45 UTC, hamelin requested changes
The notebook file `doc/sparse_metadata_cluster_labels.ipynb` is corrupted: only a prefix of the text seems to have been included by either Git or Github.

2022-12-12 14:45 UTC, hamelin commented on thisnotthat/map_cluster_labelling.py
> +    pointset_layers: List[List[npt.NDArray]],
Why make these three parameters strictly positional?

2022-12-12 14:45 UTC, hamelin commented on thisnotthat/map_cluster_labelling.py
> +        source_vectors: npt.ArrayLike,
Again: why strictly positional parameters? With such a long list of formal parameters, I would certainly use as many named parameters as I could...

2022-12-12 14:45 UTC, hamelin commented on thisnotthat/map_cluster_labelling.py
> +        (
```suggestion

        (
```

2022-12-12 14:45 UTC, hamelin commented on thisnotthat/map_cluster_labelling.py
> +        (
Reading this code I thought at first these parentheses were for calling a function returned by `build_fine_grained_cluster_centers` (which would be some wild-west idiom, but I can get behind it), and it took me a while to see it was to accept three return values from `build_cluster_layers`. I believe this line skip facilitates reading.

2022-12-12 17:54 UTC, hamelin approved these changes
I'll approve to avoid putting myself in the way, but I have a few questions dispersed between the code lines that I believe should be addressed.

2022-12-15 15:19 UTC, jc-healy approved these changes
Thanks for writing this up.  It will be handy to have in the toolbox.

2022-12-15 15:19 UTC, jc-healy commented on thisnotthat/map_cluster_labelling.py
> +        Whether to directly cluster the map representation, or use UMAP to generate a representation for clustering
```suggestion
If set to True, cluster your raw map representation.  If set to False apply UMAP first to generate a representation for clustering.
```
It's less eloquent and equivalent but a touch clearer (in my head at least) as I had to read this twice.

2023-01-29 21:49 UTC, merged